/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "C:\\Users\\nerche\\Documents\\_code\\vueblog\\node_modules\\@vuepress\\core\\lib\\app\\root-mixins\\updateMeta.js"
import m1 from "C:\\Users\\nerche\\Documents\\_code\\vueblog\\node_modules\\@vuepress\\plugin-active-header-links\\mixin.js"

export default [
  m0,
  m1
]