/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import layoutComponents from '@internal/layout-components'
import pageComponents from '@internal/page-components'
import LayoutDistributor from '@app/components/LayoutDistributor.vue'

injectComponentOption(LayoutDistributor, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3e7e4add",
    path: "/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e7e4add").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-fd85dfe4",
    path: "/about/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fd85dfe4").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-454aab4a",
    path: "/algorithm/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-454aab4a").then(next)
    },
  },
  {
    path: "/algorithm/index.html",
    redirect: "/algorithm/"
  },
  {
    name: "v-57738a84",
    path: "/README1.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57738a84").then(next)
    },
  },
  {
    name: "v-6e6d9fa4",
    path: "/algorithm/cpp/c.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e6d9fa4").then(next)
    },
  },
  {
    name: "v-370dd84f",
    path: "/algorithm/cpp/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-370dd84f").then(next)
    },
  },
  {
    path: "/algorithm/cpp/index.html",
    redirect: "/algorithm/cpp/"
  },
  {
    name: "v-ba272fb8",
    path: "/algorithm/cpp/pointer.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba272fb8").then(next)
    },
  },
  {
    name: "v-c2444d66",
    path: "/algorithm/leetcode/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c2444d66").then(next)
    },
  },
  {
    path: "/algorithm/leetcode/index.html",
    redirect: "/algorithm/leetcode/"
  },
  {
    name: "v-832bff94",
    path: "/algorithm/cpp/string.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-832bff94").then(next)
    },
  },
  {
    name: "v-33ac9f44",
    path: "/algorithm/cpp/makefile.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33ac9f44").then(next)
    },
  },
  {
    name: "v-517bd1e4",
    path: "/algorithm/cpp/map_set.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-517bd1e4").then(next)
    },
  },
  {
    name: "v-547686be",
    path: "/algorithm/leetcode/math.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-547686be").then(next)
    },
  },
  {
    name: "v-a0d646e4",
    path: "/algorithm/leetcode/stack.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a0d646e4").then(next)
    },
  },
  {
    name: "v-353066ed",
    path: "/algorithm/python/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-353066ed").then(next)
    },
  },
  {
    path: "/algorithm/python/index.html",
    redirect: "/algorithm/python/"
  },
  {
    name: "v-7f8401cc",
    path: "/algorithm/python/functions.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f8401cc").then(next)
    },
  },
  {
    name: "v-770d142d",
    path: "/algorithm/web/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-770d142d").then(next)
    },
  },
  {
    path: "/algorithm/web/index.html",
    redirect: "/algorithm/web/"
  },
  {
    name: "v-4041e5be",
    path: "/blog/2018/apt.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4041e5be").then(next)
    },
  },
  {
    name: "v-2f6c4f9a",
    path: "/algorithm/python/tools.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f6c4f9a").then(next)
    },
  },
  {
    name: "v-5f35c5fe",
    path: "/blog/2018/css.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f35c5fe").then(next)
    },
  },
  {
    name: "v-6b0efb04",
    path: "/blog/2018/flask.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b0efb04").then(next)
    },
  },
  {
    name: "v-6150efba",
    path: "/blog/2018/database.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6150efba").then(next)
    },
  },
  {
    name: "v-1949d144",
    path: "/blog/2018/jekyll.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1949d144").then(next)
    },
  },
  {
    name: "v-4b9345ee",
    path: "/blog/2018/kilo.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b9345ee").then(next)
    },
  },
  {
    name: "v-1dd71dd6",
    path: "/blog/2018/javascript.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1dd71dd6").then(next)
    },
  },
  {
    name: "v-24bcd6fe",
    path: "/blog/2018/qqbot.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24bcd6fe").then(next)
    },
  },
  {
    name: "v-340d411e",
    path: "/blog/2018/vim.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-340d411e").then(next)
    },
  },
  {
    name: "v-567f481e",
    path: "/blog/2018/linux.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-567f481e").then(next)
    },
  },
  {
    name: "v-1fb72b9e",
    path: "/blog/2018/vue.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fb72b9e").then(next)
    },
  },
  {
    name: "v-356ecdde",
    path: "/blog/2018/vueblog.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-356ecdde").then(next)
    },
  },
  {
    name: "v-49b0b93e",
    path: "/blog/2018/vue-cli.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49b0b93e").then(next)
    },
  },
  {
    name: "v-5db24ecc",
    path: "/blog/2018/webquicknote.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5db24ecc").then(next)
    },
  },
  {
    name: "v-03216b33",
    path: "/blog/project/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03216b33").then(next)
    },
  },
  {
    path: "/blog/project/index.html",
    redirect: "/blog/project/"
  },
  {
    name: "v-64057480",
    path: "/blog/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64057480").then(next)
    },
  },
  {
    path: "/blog/index.html",
    redirect: "/blog/"
  },
  {
    name: "v-95eb70c8",
    path: "/blog/project/qqbot.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-95eb70c8").then(next)
    },
  },
  {
    name: "v-79683b90",
    path: "/blog/project/kilo.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79683b90").then(next)
    },
  },
  {
    name: "v-42841590",
    path: "/blog/project/jekyll.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42841590").then(next)
    },
  },
  {
    name: "v-7e22f65a",
    path: "/blog/project/vueblog.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e22f65a").then(next)
    },
  },
  {
    name: "v-36900551",
    path: "/blog/tool/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36900551").then(next)
    },
  },
  {
    path: "/blog/tool/index.html",
    redirect: "/blog/tool/"
  },
  {
    name: "v-273616ea",
    path: "/blog/research/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-273616ea").then(next)
    },
  },
  {
    path: "/blog/research/index.html",
    redirect: "/blog/research/"
  },
  {
    name: "v-c1579544",
    path: "/blog/tool/apt.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c1579544").then(next)
    },
  },
  {
    name: "v-d9c0de84",
    path: "/blog/tool/vim.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d9c0de84").then(next)
    },
  },
  {
    name: "v-07b9c9da",
    path: "/blog/web/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07b9c9da").then(next)
    },
  },
  {
    path: "/blog/web/index.html",
    redirect: "/blog/web/"
  },
  {
    name: "v-0d178d2e",
    path: "/blog/web/css.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d178d2e").then(next)
    },
  },
  {
    name: "v-38329b50",
    path: "/blog/web/database.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38329b50").then(next)
    },
  },
  {
    name: "v-4064300e",
    path: "/blog/web/flask.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4064300e").then(next)
    },
  },
  {
    name: "v-3142eefc",
    path: "/blog/web/vue-cli.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3142eefc").then(next)
    },
  },
  {
    name: "v-81f4fe50",
    path: "/blog/web/javascript.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81f4fe50").then(next)
    },
  },
  {
    name: "v-01e717e8",
    path: "/blog/web/vue.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01e717e8").then(next)
    },
  },
  {
    name: "v-71e4c773",
    path: "/blog/zen/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71e4c773").then(next)
    },
  },
  {
    path: "/blog/zen/index.html",
    redirect: "/blog/zen/"
  },
  {
    name: "v-6ba4d858",
    path: "/blog/zen/thoughts.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ba4d858").then(next)
    },
  },
  {
    name: "v-3e8d19d8",
    path: "/books/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e8d19d8").then(next)
    },
  },
  {
    path: "/books/index.html",
    redirect: "/books/"
  },
  {
    name: "v-293c9b51",
    path: "/books/coder.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-293c9b51").then(next)
    },
  },
  {
    name: "v-6dada011",
    path: "/books/cpp.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6dada011").then(next)
    },
  },
  {
    name: "v-1ea84731",
    path: "/books/mongo.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ea84731").then(next)
    },
  },
  {
    name: "v-30e752a8",
    path: "/discuss/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30e752a8").then(next)
    },
  },
  {
    path: "/discuss/index.html",
    redirect: "/discuss/"
  },
  {
    name: "v-7fe0516a",
    path: "/logs/log_nov_18.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7fe0516a").then(next)
    },
  },
  {
    name: "v-31776540",
    path: "/logs/",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31776540").then(next)
    },
  },
  {
    path: "/logs/index.html",
    redirect: "/logs/"
  },
  {
    name: "v-08aea20b",
    path: "/logs/note.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08aea20b").then(next)
    },
  },
  {
    name: "v-72543a1e",
    path: "/blog/2018/git.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72543a1e").then(next)
    },
  },
  {
    name: "v-5d32ec84",
    path: "/blog/tool/git.html",
    component: LayoutDistributor,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d32ec84").then(next)
    },
  },
  {
    path: '*',
    component: LayoutDistributor
  }
]