/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "WeiGao",
  "description": "Welcome, friend! ",
  "base": "/",
  "pages": [
    {
      "title": "Blog Index",
      "frontmatter": {},
      "regularPath": "/",
      "key": "v-3e7e4add",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "2018",
          "slug": "_2018"
        }
      ]
    },
    {
      "frontmatter": {
        "sidebar": false,
        "footer": "MIT Licensed | Copyright © 2018-present Weigao Chen"
      },
      "regularPath": "/about/",
      "key": "v-fd85dfe4",
      "path": "/about/"
    },
    {
      "title": "Algorithm",
      "frontmatter": {},
      "regularPath": "/algorithm/",
      "key": "v-454aab4a",
      "path": "/algorithm/"
    },
    {
      "frontmatter": {
        "sidebar": false,
        "footer": "MIT Licensed | Copyright © 2018-present Weigao Chen"
      },
      "regularPath": "/README1.html",
      "key": "v-57738a84",
      "path": "/README1.html",
      "headers": [
        {
          "level": 2,
          "title": "<!-- \n<!-- \n<!-- \n<!--",
          "slug": "card-test2-homepage-welcome-homeindex"
        }
      ]
    },
    {
      "title": "Vector and Iterator",
      "frontmatter": {},
      "regularPath": "/algorithm/cpp/c.html",
      "key": "v-6e6d9fa4",
      "path": "/algorithm/cpp/c.html",
      "headers": [
        {
          "level": 2,
          "title": "library vector type",
          "slug": "library-vector-type"
        },
        {
          "level": 2,
          "title": "Iterators",
          "slug": "iterators"
        },
        {
          "level": 3,
          "title": "toupper example",
          "slug": "toupper-example"
        },
        {
          "level": 3,
          "title": "twice iterator value",
          "slug": "twice-iterator-value"
        },
        {
          "level": 3,
          "title": "Find in iterator",
          "slug": "find-in-iterator"
        }
      ]
    },
    {
      "title": "Code Content",
      "frontmatter": {},
      "regularPath": "/algorithm/cpp/",
      "key": "v-370dd84f",
      "path": "/algorithm/cpp/",
      "headers": [
        {
          "level": 2,
          "title": "Important",
          "slug": "important"
        },
        {
          "level": 2,
          "title": "String",
          "slug": "string"
        },
        {
          "level": 2,
          "title": "Map & Set",
          "slug": "map-set"
        },
        {
          "level": 2,
          "title": "C basic",
          "slug": "c-basic"
        },
        {
          "level": 2,
          "title": "Math",
          "slug": "math"
        },
        {
          "level": 2,
          "title": "STL",
          "slug": "stl"
        }
      ]
    },
    {
      "title": "Pointer",
      "frontmatter": {},
      "regularPath": "/algorithm/cpp/pointer.html",
      "key": "v-ba272fb8",
      "path": "/algorithm/cpp/pointer.html",
      "headers": [
        {
          "level": 2,
          "title": "Questions",
          "slug": "questions"
        },
        {
          "level": 2,
          "title": "pointer and array",
          "slug": "pointer-and-array"
        }
      ]
    },
    {
      "title": "Index",
      "frontmatter": {},
      "regularPath": "/algorithm/leetcode/",
      "key": "v-c2444d66",
      "path": "/algorithm/leetcode/",
      "headers": [
        {
          "level": 2,
          "title": "Math",
          "slug": "math"
        },
        {
          "level": 2,
          "title": "Stack",
          "slug": "stack"
        }
      ]
    },
    {
      "title": "String",
      "frontmatter": {},
      "regularPath": "/algorithm/cpp/string.html",
      "key": "v-832bff94",
      "path": "/algorithm/cpp/string.html",
      "headers": [
        {
          "level": 2,
          "title": "string.h",
          "slug": "string-h"
        },
        {
          "level": 3,
          "title": "memset()",
          "slug": "memset"
        },
        {
          "level": 3,
          "title": "strchr()",
          "slug": "strchr"
        },
        {
          "level": 3,
          "title": "strrchr()",
          "slug": "strrchr"
        },
        {
          "level": 3,
          "title": "strncmp and strcmp",
          "slug": "strncmp-and-strcmp"
        },
        {
          "level": 2,
          "title": "Library string Type",
          "slug": "library-string-type"
        },
        {
          "level": 3,
          "title": "getline(input stream, string)",
          "slug": "getline-input-stream-string"
        },
        {
          "level": 3,
          "title": "string::size_type",
          "slug": "string-size-type"
        },
        {
          "level": 3,
          "title": "string for",
          "slug": "string-for"
        },
        {
          "level": 3,
          "title": "toupper()",
          "slug": "toupper"
        },
        {
          "level": 3,
          "title": "Using Subscript for Iteration",
          "slug": "using-subscript-for-iteration"
        },
        {
          "level": 2,
          "title": "Additional string Operations",
          "slug": "additional-string-operations"
        },
        {
          "level": 3,
          "title": "Other ways to construct strings",
          "slug": "other-ways-to-construct-strings"
        },
        {
          "level": 3,
          "title": "substr",
          "slug": "substr"
        },
        {
          "level": 3,
          "title": "insert and replace",
          "slug": "insert-and-replace"
        },
        {
          "level": 2,
          "title": "Array and string",
          "slug": "array-and-string"
        }
      ]
    },
    {
      "title": "Makefile",
      "frontmatter": {},
      "regularPath": "/algorithm/cpp/makefile.html",
      "key": "v-33ac9f44",
      "path": "/algorithm/cpp/makefile.html"
    },
    {
      "title": "Map and Set",
      "frontmatter": {},
      "regularPath": "/algorithm/cpp/map_set.html",
      "key": "v-517bd1e4",
      "path": "/algorithm/cpp/map_set.html",
      "headers": [
        {
          "level": 2,
          "title": "unordered_map",
          "slug": "unordered-map"
        },
        {
          "level": 2,
          "title": "map",
          "slug": "map"
        },
        {
          "level": 2,
          "title": "set",
          "slug": "set"
        },
        {
          "level": 2,
          "title": "BST",
          "slug": "bst"
        },
        {
          "level": 2,
          "title": "Red-Black Tree",
          "slug": "red-black-tree"
        }
      ]
    },
    {
      "title": "Math",
      "frontmatter": {},
      "regularPath": "/algorithm/leetcode/math.html",
      "key": "v-547686be",
      "path": "/algorithm/leetcode/math.html",
      "headers": [
        {
          "level": 2,
          "title": "Bit operation",
          "slug": "bit-operation"
        },
        {
          "level": 2,
          "title": "Reverse",
          "slug": "reverse"
        }
      ]
    },
    {
      "title": "Stack",
      "frontmatter": {},
      "regularPath": "/algorithm/leetcode/stack.html",
      "key": "v-a0d646e4",
      "path": "/algorithm/leetcode/stack.html",
      "headers": [
        {
          "level": 2,
          "title": "Valid Parentheses",
          "slug": "valid-parentheses"
        }
      ]
    },
    {
      "title": "Python",
      "frontmatter": {},
      "regularPath": "/algorithm/python/",
      "key": "v-353066ed",
      "path": "/algorithm/python/",
      "headers": [
        {
          "level": 2,
          "title": "Python code Index",
          "slug": "python-code-index"
        }
      ]
    },
    {
      "title": "Built-in Functions",
      "frontmatter": {},
      "regularPath": "/algorithm/python/functions.html",
      "key": "v-7f8401cc",
      "path": "/algorithm/python/functions.html",
      "headers": [
        {
          "level": 2,
          "title": "reduce()",
          "slug": "reduce"
        },
        {
          "level": 2,
          "title": "isinstance()",
          "slug": "isinstance"
        },
        {
          "level": 2,
          "title": "extend() and append()",
          "slug": "extend-and-append"
        },
        {
          "level": 2,
          "title": "sort",
          "slug": "sort"
        },
        {
          "level": 2,
          "title": "zip",
          "slug": "zip"
        },
        {
          "level": 2,
          "title": "enumerate",
          "slug": "enumerate"
        }
      ]
    },
    {
      "title": "JS code",
      "frontmatter": {},
      "regularPath": "/algorithm/web/",
      "key": "v-770d142d",
      "path": "/algorithm/web/",
      "headers": [
        {
          "level": 2,
          "title": "eval()",
          "slug": "eval"
        }
      ]
    },
    {
      "title": "Source",
      "frontmatter": {},
      "regularPath": "/blog/2018/apt.html",
      "key": "v-4041e5be",
      "path": "/blog/2018/apt.html",
      "headers": [
        {
          "level": 2,
          "title": "apt source",
          "slug": "apt-source"
        },
        {
          "level": 2,
          "title": "pip source",
          "slug": "pip-source"
        },
        {
          "level": 2,
          "title": "gem source",
          "slug": "gem-source"
        }
      ]
    },
    {
      "title": "Tools",
      "frontmatter": {},
      "regularPath": "/algorithm/python/tools.html",
      "key": "v-2f6c4f9a",
      "path": "/algorithm/python/tools.html",
      "headers": [
        {
          "level": 2,
          "title": "IPython",
          "slug": "ipython"
        },
        {
          "level": 2,
          "title": "urllib",
          "slug": "urllib"
        },
        {
          "level": 3,
          "title": "Reading json file from URL",
          "slug": "reading-json-file-from-url"
        }
      ]
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/blog/2018/css.html",
      "key": "v-5f35c5fe",
      "path": "/blog/2018/css.html",
      "headers": [
        {
          "level": 2,
          "title": "Insert CSS",
          "slug": "insert-css"
        },
        {
          "level": 3,
          "title": "Multiple Style Sheets",
          "slug": "multiple-style-sheets"
        },
        {
          "level": 2,
          "title": "colors",
          "slug": "colors"
        }
      ]
    },
    {
      "title": "Flask",
      "frontmatter": {},
      "regularPath": "/blog/2018/flask.html",
      "key": "v-6b0efb04",
      "path": "/blog/2018/flask.html",
      "headers": [
        {
          "level": 2,
          "title": "Reference",
          "slug": "reference"
        },
        {
          "level": 2,
          "title": "SocketIO",
          "slug": "socketio"
        },
        {
          "level": 2,
          "title": "Flask Structure",
          "slug": "flask-structure"
        },
        {
          "level": 2,
          "title": "Blueprint",
          "slug": "blueprint"
        },
        {
          "level": 2,
          "title": "Virtual environment",
          "slug": "virtual-environment"
        },
        {
          "level": 3,
          "title": "Installation",
          "slug": "installation"
        },
        {
          "level": 3,
          "title": "Usage",
          "slug": "usage"
        },
        {
          "level": 2,
          "title": "Requirement.txt",
          "slug": "requirement-txt"
        },
        {
          "level": 2,
          "title": "Video Streaming with Flask",
          "slug": "video-streaming-with-flask"
        },
        {
          "level": 2,
          "title": "Flask Script",
          "slug": "flask-script"
        },
        {
          "level": 2,
          "title": "Web Server",
          "slug": "web-server"
        },
        {
          "level": 3,
          "title": "WSGI",
          "slug": "wsgi"
        },
        {
          "level": 3,
          "title": "Nginx",
          "slug": "nginx"
        },
        {
          "level": 2,
          "title": "Django",
          "slug": "django"
        },
        {
          "level": 3,
          "title": "Installation",
          "slug": "installation-2"
        },
        {
          "level": 3,
          "title": "Establish application",
          "slug": "establish-application"
        },
        {
          "level": 2,
          "title": "New Words",
          "slug": "new-words"
        }
      ]
    },
    {
      "title": "MongoDB",
      "frontmatter": {},
      "regularPath": "/blog/2018/database.html",
      "key": "v-6150efba",
      "path": "/blog/2018/database.html",
      "headers": [
        {
          "level": 2,
          "title": "CRUD",
          "slug": "crud"
        },
        {
          "level": 3,
          "title": "Cteate",
          "slug": "cteate"
        },
        {
          "level": 3,
          "title": "Read",
          "slug": "read"
        },
        {
          "level": 3,
          "title": "Update",
          "slug": "update"
        },
        {
          "level": 3,
          "title": "Delate",
          "slug": "delate"
        },
        {
          "level": 3,
          "title": "Restore",
          "slug": "restore"
        },
        {
          "level": 2,
          "title": "Flask-PyMongo",
          "slug": "flask-pymongo"
        },
        {
          "level": 2,
          "title": "Python SQL",
          "slug": "python-sql"
        },
        {
          "level": 2,
          "title": "SQLite3",
          "slug": "sqlite3"
        }
      ]
    },
    {
      "title": "Jekyll",
      "frontmatter": {},
      "regularPath": "/blog/2018/jekyll.html",
      "key": "v-1949d144",
      "path": "/blog/2018/jekyll.html",
      "headers": [
        {
          "level": 2,
          "title": "GitHub Pages",
          "slug": "github-pages"
        },
        {
          "level": 2,
          "title": "Install",
          "slug": "install"
        },
        {
          "level": 2,
          "title": "Build Site",
          "slug": "build-site"
        },
        {
          "level": 2,
          "title": "Blog Directory Structure",
          "slug": "blog-directory-structure"
        },
        {
          "level": 2,
          "title": "Add Post",
          "slug": "add-post"
        },
        {
          "level": 2,
          "title": "Publish Blog",
          "slug": "publish-blog"
        },
        {
          "level": 2,
          "title": "Highlight Code",
          "slug": "highlight-code"
        },
        {
          "level": 2,
          "title": "Including Images and resources",
          "slug": "including-images-and-resources"
        },
        {
          "level": 2,
          "title": "Add HTTPS",
          "slug": "add-https"
        },
        {
          "level": 2,
          "title": "highlight.js",
          "slug": "highlight-js"
        }
      ]
    },
    {
      "title": "Kilo Text Editor",
      "frontmatter": {},
      "regularPath": "/blog/2018/kilo.html",
      "key": "v-4b9345ee",
      "path": "/blog/2018/kilo.html",
      "headers": [
        {
          "level": 2,
          "title": "Features",
          "slug": "features"
        },
        {
          "level": 2,
          "title": "Key Concept",
          "slug": "key-concept"
        },
        {
          "level": 2,
          "title": "Useful Skills",
          "slug": "useful-skills"
        }
      ]
    },
    {
      "title": "JavaScript",
      "frontmatter": {},
      "regularPath": "/blog/2018/javascript.html",
      "key": "v-1dd71dd6",
      "path": "/blog/2018/javascript.html",
      "headers": [
        {
          "level": 2,
          "title": "Date/Time",
          "slug": "date-time"
        },
        {
          "level": 3,
          "title": "Example 1",
          "slug": "example-1"
        },
        {
          "level": 3,
          "title": "Example 2",
          "slug": "example-2"
        },
        {
          "level": 3,
          "title": "Example 3",
          "slug": "example-3"
        },
        {
          "level": 3,
          "title": "Example 4",
          "slug": "example-4"
        },
        {
          "level": 2,
          "title": "Performance",
          "slug": "performance"
        },
        {
          "level": 2,
          "title": "localStorage",
          "slug": "localstorage"
        },
        {
          "level": 2,
          "title": "Var, Let and Const",
          "slug": "var-let-and-const"
        }
      ]
    },
    {
      "title": "qqbot",
      "frontmatter": {},
      "regularPath": "/blog/2018/qqbot.html",
      "key": "v-24bcd6fe",
      "path": "/blog/2018/qqbot.html",
      "headers": [
        {
          "level": 2,
          "title": "Overview",
          "slug": "overview"
        },
        {
          "level": 2,
          "title": "Plugin",
          "slug": "plugin"
        },
        {
          "level": 2,
          "title": "Create a bot",
          "slug": "create-a-bot"
        },
        {
          "level": 2,
          "title": "urllib, url request",
          "slug": "urllib-url-request"
        },
        {
          "level": 2,
          "title": "Timed transmission",
          "slug": "timed-transmission"
        }
      ]
    },
    {
      "title": "Vim",
      "frontmatter": {},
      "regularPath": "/blog/2018/vim.html",
      "key": "v-340d411e",
      "path": "/blog/2018/vim.html",
      "headers": [
        {
          "level": 2,
          "title": "reference",
          "slug": "reference"
        },
        {
          "level": 2,
          "title": "Plugin Manager",
          "slug": "plugin-manager"
        }
      ]
    },
    {
      "title": "Linux",
      "frontmatter": {},
      "regularPath": "/blog/2018/linux.html",
      "key": "v-567f481e",
      "path": "/blog/2018/linux.html",
      "headers": [
        {
          "level": 2,
          "title": "ssh",
          "slug": "ssh"
        },
        {
          "level": 2,
          "title": "File server",
          "slug": "file-server"
        },
        {
          "level": 2,
          "title": "program status",
          "slug": "program-status"
        }
      ]
    },
    {
      "title": "Vue",
      "frontmatter": {},
      "regularPath": "/blog/2018/vue.html",
      "key": "v-1fb72b9e",
      "path": "/blog/2018/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "Animating State",
          "slug": "animating-state"
        },
        {
          "level": 2,
          "title": "axios",
          "slug": "axios"
        },
        {
          "level": 2,
          "title": "Devtools",
          "slug": "devtools"
        },
        {
          "level": 2,
          "title": "components",
          "slug": "components"
        },
        {
          "level": 3,
          "title": "register",
          "slug": "register"
        },
        {
          "level": 2,
          "title": "Filters",
          "slug": "filters"
        },
        {
          "level": 2,
          "title": "Directives",
          "slug": "directives"
        },
        {
          "level": 3,
          "title": "v-cloak",
          "slug": "v-cloak"
        },
        {
          "level": 3,
          "title": "v-text",
          "slug": "v-text"
        },
        {
          "level": 3,
          "title": "v-html",
          "slug": "v-html"
        },
        {
          "level": 3,
          "title": "v-bind",
          "slug": "v-bind"
        },
        {
          "level": 3,
          "title": "v-on",
          "slug": "v-on"
        },
        {
          "level": 3,
          "title": "key modifiers",
          "slug": "key-modifiers"
        },
        {
          "level": 3,
          "title": "v-model",
          "slug": "v-model"
        },
        {
          "level": 3,
          "title": "Custom Directives",
          "slug": "custom-directives"
        },
        {
          "level": 2,
          "title": "Pre-Processors",
          "slug": "pre-processors"
        }
      ]
    },
    {
      "title": "Vueblog",
      "frontmatter": {},
      "regularPath": "/blog/2018/vueblog.html",
      "key": "v-356ecdde",
      "path": "/blog/2018/vueblog.html",
      "headers": [
        {
          "level": 2,
          "title": "vuepress update",
          "slug": "vuepress-update"
        },
        {
          "level": 2,
          "title": "Theme config",
          "slug": "theme-config"
        },
        {
          "level": 3,
          "title": "custom containers",
          "slug": "custom-containers"
        },
        {
          "level": 3,
          "title": "icons",
          "slug": "icons"
        },
        {
          "level": 3,
          "title": "code collapsing",
          "slug": "code-collapsing"
        }
      ]
    },
    {
      "title": "Vue CLI",
      "frontmatter": {},
      "regularPath": "/blog/2018/vue-cli.html",
      "key": "v-49b0b93e",
      "path": "/blog/2018/vue-cli.html"
    },
    {
      "title": "Quick Note",
      "frontmatter": {},
      "regularPath": "/blog/2018/webquicknote.html",
      "key": "v-5db24ecc",
      "path": "/blog/2018/webquicknote.html"
    },
    {
      "title": "README",
      "frontmatter": {},
      "regularPath": "/blog/project/",
      "key": "v-03216b33",
      "path": "/blog/project/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/",
      "key": "v-64057480",
      "path": "/blog/"
    },
    {
      "title": "qqbot",
      "frontmatter": {},
      "regularPath": "/blog/project/qqbot.html",
      "key": "v-95eb70c8",
      "path": "/blog/project/qqbot.html",
      "headers": [
        {
          "level": 2,
          "title": "Overview",
          "slug": "overview"
        },
        {
          "level": 2,
          "title": "Plugin",
          "slug": "plugin"
        },
        {
          "level": 2,
          "title": "Create a bot",
          "slug": "create-a-bot"
        },
        {
          "level": 2,
          "title": "urllib, url request",
          "slug": "urllib-url-request"
        },
        {
          "level": 2,
          "title": "Timed transmission",
          "slug": "timed-transmission"
        }
      ]
    },
    {
      "title": "Kilo Text Editor",
      "frontmatter": {},
      "regularPath": "/blog/project/kilo.html",
      "key": "v-79683b90",
      "path": "/blog/project/kilo.html",
      "headers": [
        {
          "level": 2,
          "title": "Features",
          "slug": "features"
        },
        {
          "level": 2,
          "title": "Key Concept",
          "slug": "key-concept"
        },
        {
          "level": 2,
          "title": "Useful Skills",
          "slug": "useful-skills"
        }
      ]
    },
    {
      "title": "Jekyll",
      "frontmatter": {},
      "regularPath": "/blog/project/jekyll.html",
      "key": "v-42841590",
      "path": "/blog/project/jekyll.html",
      "headers": [
        {
          "level": 2,
          "title": "GitHub Pages",
          "slug": "github-pages"
        },
        {
          "level": 2,
          "title": "Install",
          "slug": "install"
        },
        {
          "level": 2,
          "title": "Build Site",
          "slug": "build-site"
        },
        {
          "level": 2,
          "title": "Blog Directory Structure",
          "slug": "blog-directory-structure"
        },
        {
          "level": 2,
          "title": "Add Post",
          "slug": "add-post"
        },
        {
          "level": 2,
          "title": "Publish Blog",
          "slug": "publish-blog"
        },
        {
          "level": 2,
          "title": "Highlight Code",
          "slug": "highlight-code"
        },
        {
          "level": 2,
          "title": "Including Images and resources",
          "slug": "including-images-and-resources"
        },
        {
          "level": 2,
          "title": "Add HTTPS",
          "slug": "add-https"
        },
        {
          "level": 2,
          "title": "highlight.js",
          "slug": "highlight-js"
        }
      ]
    },
    {
      "title": "Vueblog",
      "frontmatter": {},
      "regularPath": "/blog/project/vueblog.html",
      "key": "v-7e22f65a",
      "path": "/blog/project/vueblog.html",
      "headers": [
        {
          "level": 2,
          "title": "vuepress update",
          "slug": "vuepress-update"
        },
        {
          "level": 2,
          "title": "Theme config",
          "slug": "theme-config"
        },
        {
          "level": 3,
          "title": "custom containers",
          "slug": "custom-containers"
        },
        {
          "level": 3,
          "title": "icons",
          "slug": "icons"
        },
        {
          "level": 3,
          "title": "code collapsing",
          "slug": "code-collapsing"
        }
      ]
    },
    {
      "title": "Linux",
      "frontmatter": {},
      "regularPath": "/blog/tool/",
      "key": "v-36900551",
      "path": "/blog/tool/",
      "headers": [
        {
          "level": 2,
          "title": "ssh",
          "slug": "ssh"
        },
        {
          "level": 2,
          "title": "File server",
          "slug": "file-server"
        },
        {
          "level": 2,
          "title": "program status",
          "slug": "program-status"
        }
      ]
    },
    {
      "title": "Research",
      "frontmatter": {},
      "regularPath": "/blog/research/",
      "key": "v-273616ea",
      "path": "/blog/research/"
    },
    {
      "title": "Source",
      "frontmatter": {},
      "regularPath": "/blog/tool/apt.html",
      "key": "v-c1579544",
      "path": "/blog/tool/apt.html",
      "headers": [
        {
          "level": 2,
          "title": "apt source",
          "slug": "apt-source"
        },
        {
          "level": 2,
          "title": "pip source",
          "slug": "pip-source"
        },
        {
          "level": 2,
          "title": "gem source",
          "slug": "gem-source"
        }
      ]
    },
    {
      "title": "Vim",
      "frontmatter": {},
      "regularPath": "/blog/tool/vim.html",
      "key": "v-d9c0de84",
      "path": "/blog/tool/vim.html",
      "headers": [
        {
          "level": 2,
          "title": "reference",
          "slug": "reference"
        },
        {
          "level": 2,
          "title": "Plugin Manager",
          "slug": "plugin-manager"
        }
      ]
    },
    {
      "title": "Quick Note",
      "frontmatter": {},
      "regularPath": "/blog/web/",
      "key": "v-07b9c9da",
      "path": "/blog/web/"
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/blog/web/css.html",
      "key": "v-0d178d2e",
      "path": "/blog/web/css.html",
      "headers": [
        {
          "level": 2,
          "title": "Insert CSS",
          "slug": "insert-css"
        },
        {
          "level": 3,
          "title": "Multiple Style Sheets",
          "slug": "multiple-style-sheets"
        },
        {
          "level": 2,
          "title": "colors",
          "slug": "colors"
        }
      ]
    },
    {
      "title": "MongoDB",
      "frontmatter": {},
      "regularPath": "/blog/web/database.html",
      "key": "v-38329b50",
      "path": "/blog/web/database.html",
      "headers": [
        {
          "level": 2,
          "title": "CRUD",
          "slug": "crud"
        },
        {
          "level": 3,
          "title": "Cteate",
          "slug": "cteate"
        },
        {
          "level": 3,
          "title": "Read",
          "slug": "read"
        },
        {
          "level": 3,
          "title": "Update",
          "slug": "update"
        },
        {
          "level": 3,
          "title": "Delate",
          "slug": "delate"
        },
        {
          "level": 3,
          "title": "Restore",
          "slug": "restore"
        },
        {
          "level": 2,
          "title": "Flask-PyMongo",
          "slug": "flask-pymongo"
        },
        {
          "level": 2,
          "title": "Python SQL",
          "slug": "python-sql"
        },
        {
          "level": 2,
          "title": "SQLite3",
          "slug": "sqlite3"
        }
      ]
    },
    {
      "title": "Flask",
      "frontmatter": {},
      "regularPath": "/blog/web/flask.html",
      "key": "v-4064300e",
      "path": "/blog/web/flask.html",
      "headers": [
        {
          "level": 2,
          "title": "Reference",
          "slug": "reference"
        },
        {
          "level": 2,
          "title": "SocketIO",
          "slug": "socketio"
        },
        {
          "level": 2,
          "title": "Flask Structure",
          "slug": "flask-structure"
        },
        {
          "level": 2,
          "title": "Blueprint",
          "slug": "blueprint"
        },
        {
          "level": 2,
          "title": "Virtual environment",
          "slug": "virtual-environment"
        },
        {
          "level": 3,
          "title": "Installation",
          "slug": "installation"
        },
        {
          "level": 3,
          "title": "Usage",
          "slug": "usage"
        },
        {
          "level": 2,
          "title": "Requirement.txt",
          "slug": "requirement-txt"
        },
        {
          "level": 2,
          "title": "Video Streaming with Flask",
          "slug": "video-streaming-with-flask"
        },
        {
          "level": 2,
          "title": "Flask Script",
          "slug": "flask-script"
        },
        {
          "level": 2,
          "title": "Web Server",
          "slug": "web-server"
        },
        {
          "level": 3,
          "title": "WSGI",
          "slug": "wsgi"
        },
        {
          "level": 3,
          "title": "Nginx",
          "slug": "nginx"
        },
        {
          "level": 2,
          "title": "Django",
          "slug": "django"
        },
        {
          "level": 3,
          "title": "Installation",
          "slug": "installation-2"
        },
        {
          "level": 3,
          "title": "Establish application",
          "slug": "establish-application"
        },
        {
          "level": 2,
          "title": "New Words",
          "slug": "new-words"
        }
      ]
    },
    {
      "title": "Vue CLI",
      "frontmatter": {},
      "regularPath": "/blog/web/vue-cli.html",
      "key": "v-3142eefc",
      "path": "/blog/web/vue-cli.html"
    },
    {
      "title": "JavaScript",
      "frontmatter": {},
      "regularPath": "/blog/web/javascript.html",
      "key": "v-81f4fe50",
      "path": "/blog/web/javascript.html",
      "headers": [
        {
          "level": 2,
          "title": "Date/Time",
          "slug": "date-time"
        },
        {
          "level": 3,
          "title": "Example 1",
          "slug": "example-1"
        },
        {
          "level": 3,
          "title": "Example 2",
          "slug": "example-2"
        },
        {
          "level": 3,
          "title": "Example 3",
          "slug": "example-3"
        },
        {
          "level": 3,
          "title": "Example 4",
          "slug": "example-4"
        },
        {
          "level": 2,
          "title": "Performance",
          "slug": "performance"
        },
        {
          "level": 2,
          "title": "localStorage",
          "slug": "localstorage"
        },
        {
          "level": 2,
          "title": "Var, Let and Const",
          "slug": "var-let-and-const"
        }
      ]
    },
    {
      "title": "Vue",
      "frontmatter": {},
      "regularPath": "/blog/web/vue.html",
      "key": "v-01e717e8",
      "path": "/blog/web/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "Animating State",
          "slug": "animating-state"
        },
        {
          "level": 2,
          "title": "axios",
          "slug": "axios"
        },
        {
          "level": 2,
          "title": "Devtools",
          "slug": "devtools"
        },
        {
          "level": 2,
          "title": "components",
          "slug": "components"
        },
        {
          "level": 3,
          "title": "register",
          "slug": "register"
        },
        {
          "level": 2,
          "title": "Filters",
          "slug": "filters"
        },
        {
          "level": 2,
          "title": "Directives",
          "slug": "directives"
        },
        {
          "level": 3,
          "title": "v-cloak",
          "slug": "v-cloak"
        },
        {
          "level": 3,
          "title": "v-text",
          "slug": "v-text"
        },
        {
          "level": 3,
          "title": "v-html",
          "slug": "v-html"
        },
        {
          "level": 3,
          "title": "v-bind",
          "slug": "v-bind"
        },
        {
          "level": 3,
          "title": "v-on",
          "slug": "v-on"
        },
        {
          "level": 3,
          "title": "key modifiers",
          "slug": "key-modifiers"
        },
        {
          "level": 3,
          "title": "v-model",
          "slug": "v-model"
        },
        {
          "level": 3,
          "title": "Custom Directives",
          "slug": "custom-directives"
        },
        {
          "level": 2,
          "title": "Pre-Processors",
          "slug": "pre-processors"
        }
      ]
    },
    {
      "title": "The Zen of Python",
      "frontmatter": {},
      "regularPath": "/blog/zen/",
      "key": "v-71e4c773",
      "path": "/blog/zen/"
    },
    {
      "title": "Thoughts",
      "frontmatter": {},
      "regularPath": "/blog/zen/thoughts.html",
      "key": "v-6ba4d858",
      "path": "/blog/zen/thoughts.html"
    },
    {
      "title": "Index",
      "frontmatter": {
        "title": "Index",
        "description": "Book Reading List"
      },
      "regularPath": "/books/",
      "key": "v-3e8d19d8",
      "path": "/books/"
    },
    {
      "title": "Coder Book",
      "frontmatter": {
        "title": "Coder Book",
        "description": "Computer Basic Knowledges"
      },
      "regularPath": "/books/coder.html",
      "key": "v-293c9b51",
      "path": "/books/coder.html",
      "headers": [
        {
          "level": 2,
          "title": "Thread and Process",
          "slug": "thread-and-process"
        },
        {
          "level": 3,
          "title": "进程",
          "slug": "进程"
        },
        {
          "level": 2,
          "title": "TCP/IP Socket",
          "slug": "tcp-ip-socket"
        },
        {
          "level": 3,
          "title": "TCP/IP",
          "slug": "tcp-ip"
        },
        {
          "level": 3,
          "title": "CPU",
          "slug": "cpu"
        }
      ],
      "excerpt": "<p>An application consists of one or more processes. A process, in the simplest terms, is an executing program. One or more threads run in the context of the process. A thread is the basic unit to which the operating system allocates processor time. A thread can execute any part of the process code, including parts currently being executed by another thread.</p>\n"
    },
    {
      "title": "C++ Prime",
      "frontmatter": {
        "title": "C++ Prime",
        "description": "C++ prime book"
      },
      "regularPath": "/books/cpp.html",
      "key": "v-6dada011",
      "path": "/books/cpp.html",
      "headers": [
        {
          "level": 2,
          "title": "Some Notes",
          "slug": "some-notes"
        },
        {
          "level": 3,
          "title": "变量和初始化",
          "slug": "变量和初始化"
        },
        {
          "level": 3,
          "title": "File Redirection",
          "slug": "file-redirection"
        },
        {
          "level": 3,
          "title": "I/O",
          "slug": "i-o"
        },
        {
          "level": 3,
          "title": "sizeof",
          "slug": "sizeof"
        },
        {
          "level": 3,
          "title": "remove_if",
          "slug": "remove-if"
        },
        {
          "level": 3,
          "title": "snprintf",
          "slug": "snprintf"
        },
        {
          "level": 2,
          "title": "Variadic function",
          "slug": "variadic-function"
        },
        {
          "level": 2,
          "title": "Type",
          "slug": "type"
        },
        {
          "level": 3,
          "title": "Compound Types",
          "slug": "compound-types"
        },
        {
          "level": 3,
          "title": "reference",
          "slug": "reference"
        },
        {
          "level": 2,
          "title": "IO",
          "slug": "io"
        },
        {
          "level": 3,
          "title": "Output buffer",
          "slug": "output-buffer"
        },
        {
          "level": 2,
          "title": "String",
          "slug": "string"
        },
        {
          "level": 3,
          "title": "Initialization",
          "slug": "initialization"
        },
        {
          "level": 3,
          "title": "Dealing with Types",
          "slug": "dealing-with-types"
        },
        {
          "level": 3,
          "title": "decltype Type Specifier",
          "slug": "decltype-type-specifier"
        },
        {
          "level": 2,
          "title": "Vector and Iterator",
          "slug": "vector-and-iterator"
        },
        {
          "level": 3,
          "title": "Iterator Init",
          "slug": "iterator-init"
        },
        {
          "level": 2,
          "title": "Using Iterators",
          "slug": "using-iterators"
        },
        {
          "level": 2,
          "title": "Sequential Containers",
          "slug": "sequential-containers"
        },
        {
          "level": 3,
          "title": "Overview",
          "slug": "overview"
        }
      ],
      "excerpt": "<pre class=\"vue-container\"><code><p>This is a reading note when I studying C++ basic grammar</p>\n<p>some from book: 《C Primer》</p>\n</code></pre>"
    },
    {
      "title": "MongoDB",
      "frontmatter": {
        "title": "MongoDB",
        "description": "The Definitive Guide to MongoDB"
      },
      "regularPath": "/books/mongo.html",
      "key": "v-1ea84731",
      "path": "/books/mongo.html",
      "headers": [
        {
          "level": 2,
          "title": "_id",
          "slug": "id"
        },
        {
          "level": 2,
          "title": "Index",
          "slug": "index"
        }
      ],
      "excerpt": "<p>A complete guide to dealing with big date using mongodb, third edition.</p>\n"
    },
    {
      "title": "Message Board",
      "frontmatter": {
        "sidebar": false,
        "footer": "MIT Licensed | Copyright © 2018-present Weigao Chen"
      },
      "regularPath": "/discuss/",
      "key": "v-30e752a8",
      "path": "/discuss/",
      "headers": [
        {
          "level": 2,
          "title": "Message Board",
          "slug": "message-board"
        }
      ]
    },
    {
      "title": "November Log",
      "frontmatter": {},
      "regularPath": "/logs/log_nov_18.html",
      "key": "v-7fe0516a",
      "path": "/logs/log_nov_18.html",
      "headers": [
        {
          "level": 2,
          "title": "Abstract",
          "slug": "abstract"
        },
        {
          "level": 2,
          "title": "Plugins",
          "slug": "plugins"
        },
        {
          "level": 2,
          "title": "Functions",
          "slug": "functions"
        }
      ]
    },
    {
      "title": "2018/work log",
      "frontmatter": {},
      "regularPath": "/logs/",
      "key": "v-31776540",
      "path": "/logs/",
      "headers": [
        {
          "level": 2,
          "title": "July",
          "slug": "july"
        },
        {
          "level": 2,
          "title": "August",
          "slug": "august"
        },
        {
          "level": 2,
          "title": "September",
          "slug": "september"
        },
        {
          "level": 2,
          "title": "October",
          "slug": "october"
        },
        {
          "level": 2,
          "title": "November",
          "slug": "november"
        },
        {
          "level": 2,
          "title": "December",
          "slug": "december"
        }
      ]
    },
    {
      "title": "Note",
      "frontmatter": {},
      "regularPath": "/logs/note.html",
      "key": "v-08aea20b",
      "path": "/logs/note.html",
      "headers": [
        {
          "level": 2,
          "title": "URLs",
          "slug": "urls"
        },
        {
          "level": 2,
          "title": "vuepress",
          "slug": "vuepress"
        }
      ]
    },
    {
      "title": "Git",
      "frontmatter": {},
      "regularPath": "/blog/2018/git.html",
      "key": "v-72543a1e",
      "path": "/blog/2018/git.html",
      "headers": [
        {
          "level": 2,
          "title": "ssh",
          "slug": "ssh"
        },
        {
          "level": 2,
          "title": "git config",
          "slug": "git-config"
        },
        {
          "level": 2,
          "title": "GitHub accelerate",
          "slug": "github-accelerate"
        },
        {
          "level": 2,
          "title": "Tag",
          "slug": "tag"
        },
        {
          "level": 2,
          "title": "Git basic",
          "slug": "git-basic"
        },
        {
          "level": 3,
          "title": "Status",
          "slug": "status"
        },
        {
          "level": 3,
          "title": "gitignore",
          "slug": "gitignore"
        },
        {
          "level": 3,
          "title": "撤销操作",
          "slug": "撤销操作"
        },
        {
          "level": 3,
          "title": "远程仓库的使用",
          "slug": "远程仓库的使用"
        },
        {
          "level": 3,
          "title": "Git别名",
          "slug": "git别名"
        },
        {
          "level": 2,
          "title": "Git Branch",
          "slug": "git-branch"
        },
        {
          "level": 3,
          "title": "分支概述",
          "slug": "分支概述"
        },
        {
          "level": 3,
          "title": "分支管理",
          "slug": "分支管理"
        },
        {
          "level": 2,
          "title": "其他有用操作",
          "slug": "其他有用操作"
        },
        {
          "level": 3,
          "title": "强制覆盖本地文件",
          "slug": "强制覆盖本地文件"
        }
      ]
    },
    {
      "title": "Git",
      "frontmatter": {},
      "regularPath": "/blog/tool/git.html",
      "key": "v-5d32ec84",
      "path": "/blog/tool/git.html",
      "headers": [
        {
          "level": 2,
          "title": "ssh",
          "slug": "ssh"
        },
        {
          "level": 2,
          "title": "git config",
          "slug": "git-config"
        },
        {
          "level": 2,
          "title": "GitHub accelerate",
          "slug": "github-accelerate"
        },
        {
          "level": 2,
          "title": "Tag",
          "slug": "tag"
        },
        {
          "level": 2,
          "title": "Git basic",
          "slug": "git-basic"
        },
        {
          "level": 3,
          "title": "Status",
          "slug": "status"
        },
        {
          "level": 3,
          "title": "gitignore",
          "slug": "gitignore"
        },
        {
          "level": 3,
          "title": "撤销操作",
          "slug": "撤销操作"
        },
        {
          "level": 3,
          "title": "远程仓库的使用",
          "slug": "远程仓库的使用"
        },
        {
          "level": 3,
          "title": "Git别名",
          "slug": "git别名"
        },
        {
          "level": 2,
          "title": "Git Branch",
          "slug": "git-branch"
        },
        {
          "level": 3,
          "title": "分支概述",
          "slug": "分支概述"
        },
        {
          "level": 3,
          "title": "分支管理",
          "slug": "分支管理"
        },
        {
          "level": 2,
          "title": "其他有用操作",
          "slug": "其他有用操作"
        },
        {
          "level": 3,
          "title": "强制覆盖本地文件",
          "slug": "强制覆盖本地文件"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": "auto",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Algorithm",
        "link": "/algorithm/"
      }
    ]
  }
}